### ISSUE TITLE
代码生成器开发需求说明

### ISSUE THREAD

**Issue by henrylee2cn** [henrylee2cn/ant#8]
通用ant命令行创建项目：
```
NAME:
   ant new - Create a new ant project

USAGE:
   ant new [command options] [arguments...]

OPTIONS:
   --script value, -s value    项目生成脚本文件的路径
   --app_path value, -p value  新项目的路径
```

工作内容描述：

- 项目生成脚本文件的格式定义与解析
- 通过脚本生成go文件

项目结构：

```
├── README.md
├── main.go
├── api
│   ├── handlers.gen.go
│   ├── handlers.go
│   ├── router.gen.go
│   └── router.go
├── logic
│   └── xxx.go
├── sdk
│   ├── rpc.gen.go
│   ├── rpc.gen_test.go
│   ├── rpc.go
│   └── rpc_test.go
└── types
    ├── types.gen.go
    └── types.go
```

当前版本存在的问题：

- 脚本中type与go type不一致
- 实际上仅粗略实现了types的代码生成，其他模块尚缺

应当升级当前代码文件：

https://github.com/henrylee2cn/ant/blob/master/cmd/ant/create/generator.go

**Comment by henrylee2cn** [comment]
@letmefly 

- 可以把`ant new`改为`ant gen`，第一次运行时创建项目，重复gen已存在的项目时更新项目中带有`.gen.go`后缀的文件
- `ant run`是热编译运行命令，它不等于go run

**Comment by letmefly** [comment]
生成的handlers.gen.go代码里面，得有一个默认的handler和router，否则生成代码时，不知道该用什么handler和router。如果把handler写到配置文件里面，显然也是不合理的。
